<?php

declare(strict_types=1);

return [
    'experiment_version' => env('SPRINT32_EXPERIMENT_VERSION', 'retrieval-sprint-32-v1'),
    'retriever' => env('SPRINT32_RETRIEVER', 'hybrid'),
    'top_k' => [5, 10],
    'minimum_score' => (float) env('SPRINT32_MINIMUM_SCORE', 0.0),
    'max_expansion_terms' => (int) env('SPRINT32_MAX_EXPANSION_TERMS', 18),
    'query_drift_warning_threshold' => (float) env('SPRINT32_QUERY_DRIFT_WARNING_THRESHOLD', 2.5),
    'modes' => [
        'baseline',
        'reference_expansion',
        'lexical_expansion',
        'doctrinal_bridge',
        'combined',
    ],
    'lexical' => [
        'minimum_token_length' => 3,
        'stopwords' => [
            'about',
            'again',
            'being',
            'does',
            'from',
            'have',
            'into',
            'the',
            'that',
            'teach',
            'teaches',
            'what',
            'where',
            'which',
            'with',
            'why',
            'was',
        ],
    ],
    'reference_patterns' => [
        '/\b(?:Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Josue|Joshua|Judges|Ruth|1\s+Kings|2\s+Kings|3\s+Kings|4\s+Kings|1\s+Samuel|2\s+Samuel|1\s+Chronicles|2\s+Chronicles|1\s+Paralipomenon|2\s+Paralipomenon|Ezra|Nehemiah|Tobit|Judith|Esther|Job|Psalms?|Proverbs|Ecclesiastes|Canticle(?:\s+of\s+Canticles)?|Wisdom|Sirach|Ecclesiasticus|Isaiah|Jeremiah|Lamentations|Baruch|Ezechiel|Ezekiel|Daniel|Osee|Hosea|Joel|Amos|Abdias|Obadiah|Jonas|Jonah|Micheas|Micah|Nahum|Habacuc|Habakkuk|Sophonias|Zephaniah|Aggeus|Haggai|Zacharias|Zechariah|Malachias|Malachi|Matthew|Mark|Luke|John|Acts|Romans|1\s+Corinthians|2\s+Corinthians|Galatians|Ephesians|Philippians|Colossians|1\s+Thessalonians|2\s+Thessalonians|1\s+Timothy|2\s+Timothy|Titus|Philemon|Hebrews|James|1\s+Peter|2\s+Peter|1\s+John|2\s+John|3\s+John|Jude|Apocalypse|Revelation|1\s+Maccabees|2\s+Maccabees)\s+\d+:\d+\b/i',
        '/\bCCC\s+\d+\b/i',
    ],
    'profiles' => [
        [
            'identifier' => 'incarnation',
            'label' => 'Incarnation',
            'triggers' => ['incarnation', 'became man', 'became flesh', 'word made flesh'],
            'terms' => ['incarnation', 'Word made flesh', 'flesh', 'dwelt among us', 'Son of God', 'John 1', 'CCC 456'],
            'reason' => 'Connects Incarnation language with Johannine and Catechism vocabulary.',
        ],
        [
            'identifier' => 'logos_divinity',
            'label' => 'Logos Divinity',
            'triggers' => ['word is god', 'word was god', 'word being god', 'divinity of the word', 'word divine', 'word is divine', 'god the word'],
            'terms' => ['Word', 'Logos', 'God', 'divine', 'beginning', 'John 1', 'Son'],
            'reason' => 'Bridges doctrinal language about the Word with biblical Logos vocabulary.',
        ],
        [
            'identifier' => 'trinity',
            'label' => 'Trinity',
            'triggers' => ['trinity', 'father son holy ghost', 'father son holy spirit', 'three persons'],
            'terms' => ['Father', 'Son', 'Holy Ghost', 'three', 'testimony', 'baptism', 'Matthew 28', '1 John 5'],
            'reason' => 'Maps Trinitarian terms to explicit biblical phrases in the corpus.',
        ],
        [
            'identifier' => 'eucharist',
            'label' => 'Eucharist',
            'triggers' => ['eucharist', 'real presence', 'eat my flesh', 'drink my blood', 'bread of life'],
            'terms' => ['flesh', 'blood', 'bread', 'life', 'chalice', 'communion', 'John 6', '1 Corinthians 10'],
            'reason' => 'Bridges sacramental language to Johannine and Pauline Eucharistic wording.',
        ],
        [
            'identifier' => 'salvation',
            'label' => 'Salvation',
            'triggers' => ['salvation', 'saved', 'justified', 'grace', 'faith works'],
            'terms' => ['saved', 'grace', 'faith', 'works', 'justified', 'life everlasting', 'John 3', 'Romans 5', 'Ephesians 2'],
            'reason' => 'Connects broad salvation language to canonical retrieval vocabulary.',
        ],
        [
            'identifier' => 'mary',
            'label' => 'Mary',
            'triggers' => ['mary', 'mother of my lord', 'full of grace', 'blessed among women'],
            'terms' => ['Mary', 'grace', 'blessed', 'mother', 'Lord', 'Gabriel', 'Elizabeth', 'Luke 1'],
            'reason' => 'Bridges Marian doctrinal language to explicit Lucan phrases.',
        ],
        [
            'identifier' => 'church',
            'label' => 'Church',
            'triggers' => ['church', 'peter', 'keys', 'apostles', 'forgive sins'],
            'terms' => ['Church', 'Peter', 'rock', 'keys', 'kingdom', 'apostles', 'sins', 'Matthew 16', 'John 20'],
            'reason' => 'Connects ecclesiology questions to explicit Scripture vocabulary.',
        ],
        [
            'identifier' => 'deuterocanonical',
            'label' => 'Deuterocanonical',
            'triggers' => ['deuterocanonical', 'tobit', 'judith', 'wisdom', 'sirach', 'baruch', 'maccabees'],
            'terms' => ['Tobit', 'Judith', 'Wisdom', 'Sirach', 'Ecclesiasticus', 'Baruch', 'Maccabees'],
            'reason' => 'Preserves Catholic canon terminology for deuterocanonical lookups.',
        ],
    ],
    'john_1_1_diagnostic_queries' => [
        'What does John 1:1 say?',
        'Explain John 1:1.',
        'Why does John 1:1 teach that the Word is God?',
        'Why do Christians believe that the Word is divine?',
        'What does the Bible teach about the divinity of the Word?',
        'How does the Gospel of John present the Word?',
    ],
];
