<?php

declare(strict_types=1);

return [
    'dataset_version' => 'retrieval-sprint-30-v1',
    'candidate_limit' => (int) env('SPRINT30_RETRIEVAL_CANDIDATE_LIMIT', 12),
    'embedding_batch_size' => (int) env('SPRINT30_RETRIEVAL_EMBEDDING_BATCH_SIZE', 64),
    'questions' => [
        ['category' => 'christology', 'question' => 'Where does Scripture call Jesus the Word made flesh?', 'expected_references' => ['John 1:14'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'christology', 'question' => 'What does John teach about the Word being God?', 'expected_references' => ['John 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'christology', 'question' => 'Where does the Catechism explain why the Word became flesh?', 'expected_references' => ['CCC 456'], 'expected_source_types' => ['catechism']],
        ['category' => 'christology', 'question' => 'Which Catechism paragraph is about the Incarnation?', 'expected_references' => ['CCC 454'], 'expected_source_types' => ['catechism']],
        ['category' => 'christology', 'question' => 'Where does Jesus say he and the Father are one?', 'expected_references' => ['John 10:30'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'christology', 'question' => 'Where does Thomas call Jesus my Lord and my God?', 'expected_references' => ['John 20:28'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'christology', 'question' => 'Where does Scripture say Christ rose on the third day?', 'expected_references' => ['1 Corinthians 15:4'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'christology', 'question' => 'Where is Jesus called the Lamb of God?', 'expected_references' => ['John 1:29', 'John 1:36'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'trinity', 'question' => 'Where does Jesus command baptism in the name of Father Son and Holy Ghost?', 'expected_references' => ['Matthew 28:19'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'trinity', 'question' => 'Where does John say there are three that give testimony in heaven?', 'expected_references' => ['1 John 5:7'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'trinity', 'question' => 'Where does Scripture say the Word was God?', 'expected_references' => ['John 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'trinity', 'question' => 'Where does the Catechism connect creation to the Holy Trinity?', 'expected_references' => ['CCC 291'], 'expected_source_types' => ['catechism']],
        ['category' => 'trinity', 'question' => 'Where is Jesus identified as God the Son in the Catechism?', 'expected_references' => ['CCC 442'], 'expected_source_types' => ['catechism']],

        ['category' => 'eucharist', 'question' => 'Where does Jesus say the bread he gives is his flesh?', 'expected_references' => ['John 6:51'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'eucharist', 'question' => 'Where does Jesus say unless you eat his flesh and drink his blood?', 'expected_references' => ['John 6:53'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'eucharist', 'question' => 'Where does Jesus say my flesh is meat indeed and my blood is drink indeed?', 'expected_references' => ['John 6:55'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'eucharist', 'question' => 'Where does Jesus say he that eateth my flesh abideth in me?', 'expected_references' => ['John 6:56'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'eucharist', 'question' => 'Where does Paul speak of the chalice of benediction and communion of Christ blood?', 'expected_references' => ['1 Corinthians 10:16'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'eucharist', 'question' => 'Where does Paul recount this is my body at the Last Supper?', 'expected_references' => ['1 Corinthians 11:24'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'baptism', 'question' => 'Where does Jesus teach that a man must be born again of water and the Holy Ghost?', 'expected_references' => ['John 3:5'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'baptism', 'question' => 'Where does Peter say be baptized every one of you?', 'expected_references' => ['Acts 2:38'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'baptism', 'question' => 'Where does Scripture say baptism now saveth you?', 'expected_references' => ['1 Peter 3:21'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'baptism', 'question' => 'Where does Paul say we are buried with Christ by baptism?', 'expected_references' => ['Romans 6:4'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'salvation', 'question' => 'Where does John say God so loved the world?', 'expected_references' => ['John 3:16'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'salvation', 'question' => 'Where does Paul say we are justified by faith?', 'expected_references' => ['Romans 5:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'salvation', 'question' => 'Where does James say faith without works is dead?', 'expected_references' => ['James 2:26'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'salvation', 'question' => 'Where does Scripture say by grace you are saved through faith?', 'expected_references' => ['Ephesians 2:8'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'salvation', 'question' => 'Where does Jesus say he who perseveres to the end shall be saved?', 'expected_references' => ['Matthew 24:13'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'mary', 'question' => 'Where does Gabriel say hail full of grace?', 'expected_references' => ['Luke 1:28'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'mary', 'question' => 'Where is Mary called blessed among women?', 'expected_references' => ['Luke 1:42'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'mary', 'question' => 'Where does Mary proclaim my soul doth magnify the Lord?', 'expected_references' => ['Luke 1:46'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'mary', 'question' => 'Where does Elizabeth call Mary the mother of my Lord?', 'expected_references' => ['Luke 1:43'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'mary', 'question' => 'Where does Jesus entrust his mother to the beloved disciple?', 'expected_references' => ['John 19:26', 'John 19:27'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'church', 'question' => 'Where does Jesus give Peter the keys of the kingdom?', 'expected_references' => ['Matthew 16:19'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'church', 'question' => 'Where does Jesus say thou art Peter and upon this rock I will build my church?', 'expected_references' => ['Matthew 16:18'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'church', 'question' => 'Where does Jesus give the apostles power to forgive sins?', 'expected_references' => ['John 20:23'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'church', 'question' => 'Where does Paul call the Church the pillar and ground of truth?', 'expected_references' => ['1 Timothy 3:15'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'church', 'question' => 'Where does Jesus pray that they all may be one?', 'expected_references' => ['John 17:21'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'sacraments', 'question' => 'Where does James teach calling the priests to anoint the sick?', 'expected_references' => ['James 5:14'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'sacraments', 'question' => 'Where does James say confess your sins one to another?', 'expected_references' => ['James 5:16'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'sacraments', 'question' => 'Where does Jesus teach what God joined together let no man put asunder?', 'expected_references' => ['Matthew 19:6'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'sacraments', 'question' => 'Where does Paul tell Timothy to neglect not the grace given by imposition of hands?', 'expected_references' => ['1 Timothy 4:14'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'prayer', 'question' => 'Where does Jesus teach the Our Father?', 'expected_references' => ['Matthew 6:9'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'prayer', 'question' => 'Where does Luke record Lord teach us to pray?', 'expected_references' => ['Luke 11:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'prayer', 'question' => 'Where does Jesus teach ask and it shall be given you?', 'expected_references' => ['Matthew 7:7'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'prayer', 'question' => 'Where does Paul say pray without ceasing?', 'expected_references' => ['1 Thessalonians 5:17'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'old_testament', 'question' => 'Where does Genesis say God created heaven and earth?', 'expected_references' => ['Genesis 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'old_testament', 'question' => 'Where does God promise Abraham that all nations shall be blessed?', 'expected_references' => ['Genesis 22:18'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'old_testament', 'question' => 'Where does Moses receive the commandment thou shalt not kill?', 'expected_references' => ['Exodus 20:13'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'old_testament', 'question' => 'Where does Isaiah prophesy a virgin shall conceive?', 'expected_references' => ['Isaiah 7:14'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'old_testament', 'question' => 'Where does Micah prophesy Bethlehem?', 'expected_references' => ['Micah 5:2'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'deuterocanonical', 'question' => 'Where does Tobit begin with Tobit of the tribe of Nephtali?', 'expected_references' => ['Tobit 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'deuterocanonical', 'question' => 'Where does Judith begin with Arphaxad king of the Medes?', 'expected_references' => ['Judith 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'deuterocanonical', 'question' => 'Where does Wisdom say love justice you that judge the earth?', 'expected_references' => ['Wisdom 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'deuterocanonical', 'question' => 'Where does Sirach begin all wisdom is from the Lord God?', 'expected_references' => ['Sirach 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'deuterocanonical', 'question' => 'Where does Baruch identify the words of the book written in Babylon?', 'expected_references' => ['Baruch 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'deuterocanonical', 'question' => 'Where does First Maccabees begin after Alexander son of Philip?', 'expected_references' => ['1 Maccabees 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'deuterocanonical', 'question' => 'Where does Second Maccabees address the brethren the Jews in Egypt?', 'expected_references' => ['2 Maccabees 1:1'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'exact_scripture', 'question' => 'What does John 1:1 say?', 'expected_references' => ['John 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'Explain John 1:14.', 'expected_references' => ['John 1:14'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does John 3:16 teach?', 'expected_references' => ['John 3:16'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does John 6:51 say?', 'expected_references' => ['John 6:51'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'Read Matthew 28:19.', 'expected_references' => ['Matthew 28:19'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What is written in Romans 5:1?', 'expected_references' => ['Romans 5:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does James 2:26 say?', 'expected_references' => ['James 2:26'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What is 1 Peter 3:21 about?', 'expected_references' => ['1 Peter 3:21'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does Luke 1:28 say?', 'expected_references' => ['Luke 1:28'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What happens in Acts 2:38?', 'expected_references' => ['Acts 2:38'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does Tobit 1:1 say?', 'expected_references' => ['Tobit 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does Wisdom 1:1 say?', 'expected_references' => ['Wisdom 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does Sirach 1:1 say?', 'expected_references' => ['Sirach 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does Baruch 1:1 say?', 'expected_references' => ['Baruch 1:1'], 'expected_source_types' => ['bible_verse']],
        ['category' => 'exact_scripture', 'question' => 'What does 2 Maccabees 1:1 say?', 'expected_references' => ['2 Maccabees 1:1'], 'expected_source_types' => ['bible_verse']],

        ['category' => 'cross_context', 'question' => 'Which Bible and Catechism sources support the Incarnation?', 'expected_references' => ['John 1:14', 'CCC 456'], 'expected_source_types' => ['bible_verse', 'catechism']],
        ['category' => 'cross_context', 'question' => 'Which sources connect Christ as Lamb of God?', 'expected_references' => ['John 1:29', 'CCC 608'], 'expected_source_types' => ['bible_verse', 'catechism']],
        ['category' => 'cross_context', 'question' => 'Which sources connect the Word with creation?', 'expected_references' => ['John 1:3', 'CCC 291'], 'expected_source_types' => ['bible_verse', 'catechism']],
        ['category' => 'cross_context', 'question' => 'Which sources speak about God the Son and the Word?', 'expected_references' => ['John 1:1', 'CCC 442'], 'expected_source_types' => ['bible_verse', 'catechism']],
        ['category' => 'cross_context', 'question' => 'Which sources include Augustine on John 1:1?', 'expected_references' => ['John 1:1', 'Catena Aurea John 1.1 (Augustine)'], 'expected_source_types' => ['bible_verse', 'church_father']],
        ['category' => 'cross_context', 'question' => 'Which sources include Chrysostom on John 1:1?', 'expected_references' => ['John 1:1', 'Catena Aurea John 1.1 (Chrysostom)'], 'expected_source_types' => ['bible_verse', 'church_father']],
        ['category' => 'cross_context', 'question' => 'Which source introduces Augustine praying to God?', 'expected_references' => ['Confessions 1.1'], 'expected_source_types' => ['church_father']],
        ['category' => 'cross_context', 'question' => 'Which catechism source asks who made the world?', 'expected_references' => ['Baltimore Catechism Lesson 1, Question 1'], 'expected_source_types' => ['catechism']],
    ],
];
