export const BIBLE_BOOKS = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  'Psalms',
  'Proverbs',
  'Isaiah',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  'Hebrews',
  'James',
  '1 Peter',
  'Revelation',
];

export const DEFAULT_BOOK = 'John';
export const DEFAULT_CHAPTER = 1;